# -*- coding: utf-8 -*-
import json
import os

# --- 1. LOCALES GENERATION ---
en_dict = {
  'gov': {
    'india': 'Government of India',
    'indiaHindi': 'भारत सरकार',
    'ministry': 'Ministry of Consumer Affairs, Food & Public Distribution',
    'manakonline': 'Manakonline (e-BIS)',
    'standardsPortal': 'Know Your Standard',
    'officialPortal': 'BIS Official Portal',
  },
  'brand': {
    'title': 'Bureau of Indian Standards',
    'subTitle': 'National Standards Body of India • Intelligent Compliance Assistant',
    'motto': 'मानक: पथप्रदर्शक: (Standards Lead the Way)',
    'tagAI': 'AI Compliance Portal',
    'ragActive': 'RAG Server Active',
    'ragOffline': 'Backend Offline',
    'installApp': 'Install App',
    'appInstalled': 'App Installed',
  },
  'nav': {
    'home': 'Product Guide',
    'chat': 'AI Assistant',
    'standards': 'Standards & QCO',
    'certification': 'Certification',
    'labs': 'Testing & Labs',
    'hallmarking': 'Hallmarking',
    'demonstration': 'Journey Flow',
    'estimator': 'Fee Estimator',
    'consumer': 'Consumer Help',
  },
  'hero': {
    'badge': 'National Standards Compliance Gateway • SIH Problem Statement 26107',
    'titlePrefix': 'Your Guide to',
    'titleStandards': 'BIS Standards',
    'titleAnd': '&',
    'titleCert': 'Certification',
    'subtitle': 'Find applicable Indian Standards, verify Quality Control Orders (QCOs), understand testing requirements, and access verified official BIS source citations — powered directly by your backend knowledge base.',
    'inputLabel': 'Tell us about your product or compliance requirement:',
    'inputPlaceholder': 'Example: I manufacture electric iron. What BIS standards, QCO mandates, and testing requirements do I need to follow?',
    'productNameLabel': 'Product Name',
    'productNamePlaceholder': 'e.g. Electric Iron, LED Bulb, Packaged Drinking Water',
    'categoryLabel': 'Industry Category',
    'scaleLabel': 'Enterprise Scale (MSME Concession)',
    'locationLabel': 'Manufacturing Location',
    'locationPlaceholder': 'e.g. Noida, UP / Mumbai, Maharashtra',
    'domesticLabel': 'Domestic Indian Manufacturer',
    'foreignLabel': 'Foreign Manufacturer (FMCS)',
    'attachPhoto': 'Attach PDF / Product Photo',
    'attachShort': 'Attach',
    'voiceQuery': 'Voice Query',
    'listening': 'Listening...',
    'startGuide': 'Start Product Certification Guide',
    'analyzing': 'Analyzing Standards with RAG Backend...',
    'samplePrompts': 'Explore Common Product Queries:',
  },
  'productGuide': {
    'title': 'BIS Product Certification Guide',
    'subtitle': 'Step-by-step regulatory compliance roadmap for',
    'step1': 'Product Profile',
    'step2': 'Applicable Standard',
    'step3': 'Certification & QCO',
    'step4': 'Testing & Labs',
    'step5': 'Documents',
    'step6': 'Application',
    'prevStep': '← Previous Step',
    'newConsultation': 'New Product Consultation',
    'printGuide': 'Print Guide',
    'msmeCalc': '50% MSME Fee Calc',
  },
  'step1': {
    'title': 'Step 1: Product Profile & Parameters',
    'subtitle': 'Confirm product category and manufacturing parameters to tailor BIS compliance.',
    'productName': 'Product Name',
    'category': 'Product Industry Category',
    'scale': 'Scale of Industry (MSME Concession)',
    'location': 'Manufacturing Facility Location',
    'domestic': 'Domestic Indian Manufacturer',
    'foreign': 'Foreign Manufacturer (FMCS)',
    'microScale': 'Micro Enterprise (50% Concession with Udyam)',
    'smallScale': 'Small Enterprise (20% Concession)',
    'mediumScale': 'Medium Enterprise',
    'largeScale': 'Large Scale Industry',
    'startupScale': 'DPIIT Recognized / Women Startup (50% Concession)',
    'continueBtn': 'Continue to Applicable Standard',
  },
  'step2': {
    'title': 'Step 2: Applicable Indian Standard',
    'subtitle': 'Official Indian Standard specification, scope, and technical parameters governing this product.',
    'codeLabel': 'Designated Indian Standard (IS Code)',
    'whyApplies': 'Why This Standard Applies',
    'scope': 'Standard Scope & Coverage',
    'relatedStandards': 'Related / Referenced Standards',
    'officialSource': 'Official BIS Ground-Truth Source',
    'viewOfficialDoc': 'Verify in Official BIS Repository',
    'continueBtn': 'Continue to Certification & QCO',
  },
  'step3': {
    'title': 'Step 3: Certification Scheme & Mandate',
    'subtitle': 'Regulatory compliance scheme, mandatory Quality Control Orders (QCO), and legal status.',
    'applicability': 'Regulatory Applicability Status',
    'mandatoryNotice': 'Mandatory by Law under Quality Control Order (QCO)',
    'voluntaryNotice': 'Voluntary Third-Party Quality Certification',
    'schemeType': 'Applicable Certification Scheme',
    'conditions': 'Key Compliance Conditions & Exemptions',
    'continueBtn': 'Continue to Testing Requirements',
  },
  'step4': {
    'title': 'Step 4: Mandatory Laboratory Testing',
    'subtitle': 'Required testing protocols, parameter limits, and laboratory facilities under the standard.',
    'requiredTests': 'Key Routine & Acceptance Tests',
    'labInfo': 'Testing Facility & Laboratory Network',
    'continueBtn': 'Continue to Document Preparation',
  },
  'step5': {
    'title': 'Step 5: Statutory Document Checklist',
    'subtitle': 'Prepare these technical files, calibration certificates, and layout drawings before filing.',
    'checklistTitle': 'Required Documentation for Application',
    'continueBtn': 'Continue to Application Journey',
  },
  'step6': {
    'title': 'Step 6: Step-by-Step Application Journey',
    'subtitle': 'Statutory process pipeline from online filing to grant of CM/L licence.',
    'timelineTitle': 'Licensing Milestones & Timeline',
    'manakonlineCTA': 'Apply Online on e-BIS Manakonline Portal',
    'restartBtn': 'Start New Product Guide',
  },
  'hallmarking': {
    'title': 'BIS Hallmarking of Gold & Silver Artefacts',
    'subtitle': 'Official purity certification and Hallmark Unique Identification (HUID) system under the BIS Act 2016.',
    'searchPlaceholder': 'Ask any hallmarking question (e.g. What are the 3 mandatory marks?, How to verify HUID?, Jeweller registration fee)...',
    'askBtn': 'Ask Hallmarking Assistant',
  },
  'demonstration': {
    'title': 'Demonstration: BIS Compliance & Certification Journeys',
    'subtitle': 'Interactive, data-driven workflow engine visualizing the end-to-end statutory process for manufacturers and jewellers.',
    'addStep': '+ Add Milestone Step',
    'resetFlow': 'Reset Default Flow',
    'productFlowTab': 'Product Certification (ISI/CRS)',
    'hallmarkingFlowTab': 'Gold & Silver Hallmarking (HUID)',
  },
  'consumer': {
    'title': 'BIS Consumer Help & Verification Gateway',
    'subtitle': 'Empowering consumers to verify genuine ISI marks, check HUID jewellery purity, and report substandard goods.',
    'searchPlaceholder': 'Ask a consumer question (e.g. How to verify CML number on BIS Care app?, What if an ISI marked helmet breaks?)...',
  },
  'assistant': {
    'title': 'BIS AI Compliance Assistant',
    'subtitle': 'Ask real-time questions, upload PDFs or product photos for standard verification.',
    'inputPlaceholder': 'Ask about this product, standards, testing labs...',
    'sendBtn': 'Send',
    'upload': 'Upload PDF / Image',
    'noInfoTitle': 'Information Not Available in Current Document Index',
    'noInfoDesc': 'This specific detail was not retrieved from the active BIS vector knowledge base. You can ask a focused question in the AI Assistant on the right.',
  },
  'common': {
    'verifiedSource': 'Verified BIS Source',
    'page': 'Page',
  },
  # Flat aliases
  's1Title': 'Step 1: Product Profile & Parameters',
  's1Subtitle': 'Confirm product category and manufacturing parameters to tailor BIS compliance.',
  's1ProductName': 'Product Name',
  's1Category': 'Product Industry Category',
  's1Scale': 'Scale of Industry (MSME Concession)',
  's1Location': 'Manufacturing Facility Location',
  's1Domestic': 'Domestic Indian Manufacturer',
  's1Foreign': 'Foreign Manufacturer (FMCS)',
  's1MicroScale': 'Micro Enterprise (50% Concession with Udyam)',
  's1SmallScale': 'Small Enterprise (20% Concession)',
  's1MediumScale': 'Medium Enterprise',
  's1LargeScale': 'Large Scale Industry',
  's1StartupScale': 'DPIIT Recognized / Women Startup (50% Concession)',
  's1ContinueBtn': 'Continue to Applicable Standard',
  's2Title': 'Step 2: Applicable Indian Standard',
  's2Subtitle': 'Official Indian Standard specification, scope, and technical parameters governing this product.',
  's2WhyApplies': 'Why This Standard Applies',
  's2Scope': 'Standard Scope & Coverage',
  's2RelatedStandards': 'Related / Referenced Standards',
  's2OfficialSource': 'Official BIS Ground-Truth Source',
  's2ViewOfficialDoc': 'Verify in Official BIS Repository',
  's2ContinueBtn': 'Continue to Certification & QCO',
  's3Title': 'Step 3: Certification Scheme & Mandate',
  's3Subtitle': 'Regulatory compliance scheme, mandatory Quality Control Orders (QCO), and legal status.',
  's3Applicability': 'Regulatory Applicability Status',
  's3MandatoryNotice': 'Mandatory by Law under Quality Control Order (QCO)',
  's3VoluntaryNotice': 'Voluntary Third-Party Quality Certification',
  's3Conditions': 'Key Compliance Conditions & Exemptions',
  's3ContinueBtn': 'Continue to Testing Requirements',
  's4Title': 'Step 4: Mandatory Laboratory Testing',
  's4Subtitle': 'Required testing protocols, parameter limits, and laboratory facilities under the standard.',
  's4RequiredTests': 'Key Routine & Acceptance Tests',
  's4LabInfo': 'Testing Facility & Laboratory Network',
  's4ContinueBtn': 'Continue to Document Preparation',
  's5Title': 'Step 5: Statutory Document Checklist',
  's5Subtitle': 'Prepare these technical files, calibration certificates, and layout drawings before filing.',
  's5ContinueBtn': 'Continue to Application Journey',
  's6Title': 'Step 6: Step-by-Step Application Journey',
  's6Subtitle': 'Statutory process pipeline from online filing to grant of CM/L licence.',
  's6TimelineTitle': 'Licensing Milestones & Timeline',
  's6ManakonlineCTA': 'Apply Online on e-BIS Manakonline Portal',
  's6RestartBtn': 'Start New Product Guide',
  'prevStepBtn': '← Previous Step',
  'printGuideBtn': 'Print Guide',
  'newConsultationBtn': 'New Product Consultation',
  'guideTitle': 'BIS Product Certification Guide',
  'guideSubtitle': 'Step-by-step regulatory compliance roadmap for',
  'step1Label': 'Product Profile',
  'step2Label': 'Applicable Standard',
  'step3Label': 'Certification & QCO',
  'step4Label': 'Testing & Labs',
  'step5Label': 'Documents',
  'step6Label': 'Application',
}

hi_dict = {
  'gov': {
    'india': 'भारत सरकार',
    'indiaHindi': 'भारत सरकार',
    'ministry': 'उपभोक्ता मामले, खाद्य और सार्वजनिक वितरण मंत्रालय',
    'manakonline': 'मानकऑनलाइन (e-BIS)',
    'standardsPortal': 'अपना मानक जानें (BIS Standards)',
    'officialPortal': 'बीआईएस आधिकारिक पोर्टल',
  },
  'brand': {
    'title': 'भारतीय मानक ब्यूरो',
    'subTitle': 'भारत का राष्ट्रीय मानक निकाय • एआई अनुपालन सहायक',
    'motto': 'मानक: पथप्रदर्शक: (मानक राह दिखाते हैं)',
    'tagAI': 'एआई अनुपालन पोर्टल',
    'ragActive': 'RAG सर्वर सक्रिय',
    'ragOffline': 'सर्वर ऑफलाइन',
    'installApp': 'ऐप इंस्टॉल करें',
    'appInstalled': 'ऐप इंस्टॉल है',
  },
  'nav': {
    'home': 'उत्पाद गाइड',
    'chat': 'एआई सहायक',
    'standards': 'मानक और QCO',
    'certification': 'प्रमाणीकरण',
    'labs': 'परीक्षण एवं लैब्स',
    'hallmarking': 'हॉलमार्किंग',
    'demonstration': 'प्रक्रिया प्रवाह',
    'estimator': 'शुल्क गणक (MSME)',
    'consumer': 'उपभोक्ता सहायता',
  },
  'hero': {
    'badge': 'राष्ट्रीय मानक अनुपालन गेटवे • SIH समस्या विवरण 26107',
    'titlePrefix': 'आपका मार्गदर्शक:',
    'titleStandards': 'बीआईएस मानक',
    'titleAnd': 'और',
    'titleCert': 'प्रमाणीकरण',
    'subtitle': 'लागू भारतीय मानक खोजें, गुणवत्ता नियंत्रण आदेश (QCO) सत्यापित करें, परीक्षण आवश्यकताओं को समझें और सत्यापित आधिकारिक बीआईएस स्रोत प्राप्त करें।',
    'inputLabel': 'अपने उत्पाद या प्रमाणीकरण आवश्यकता के बारे में बताएं:',
    'inputPlaceholder': 'उदाहरण: मैं इलेक्ट्रिक आयरन (प्रेस) बनाता हूं। मुझे किन बीआईएस मानकों, QCO नियमों और परीक्षण प्रक्रियाओं का पालन करना होगा?',
    'productNameLabel': 'उत्पाद का नाम',
    'productNamePlaceholder': 'उदा. इलेक्ट्रिक आयरन, एलईडी बल्ब, पैकेज्ड पेयजल',
    'categoryLabel': 'उद्योग श्रेणी',
    'scaleLabel': 'उद्यम का पैमाना (MSME रियायत)',
    'locationLabel': 'निर्माण इकाई का स्थान',
    'locationPlaceholder': 'उदा. नोएडा, उत्तर प्रदेश / मुंबई, महाराष्ट्र',
    'domesticLabel': 'घरेलू भारतीय निर्माता',
    'foreignLabel': 'विदेशी निर्माता (FMCS)',
    'attachPhoto': 'PDF / उत्पाद फोटो संलग्न करें',
    'attachShort': 'संलग्न करें',
    'voiceQuery': 'आवाज से पूछें',
    'listening': 'सुन रहा है...',
    'startGuide': 'उत्पाद प्रमाणीकरण गाइड शुरू करें',
    'analyzing': 'RAG बैकएंड से मानकों का विश्लेषण कर रहा है...',
    'samplePrompts': 'सामान्य उत्पाद प्रश्न देखें:',
  },
  'productGuide': {
    'title': 'बीआईएस उत्पाद प्रमाणीकरण गाइड',
    'subtitle': 'चरण-दर-चरण विनियामक अनुपालन रोडमैप:',
    'step1': 'उत्पाद प्रोफ़ाइल',
    'step2': 'लागू मानक',
    'step3': 'प्रमाणीकरण एवं QCO',
    'step4': 'परीक्षण एवं लैब्स',
    'step5': 'दस्तावेज',
    'step6': 'आवेदन प्रक्रिया',
    'prevStep': '← पिछला चरण',
    'newConsultation': 'नई उत्पाद परामर्श',
    'printGuide': 'गाइड प्रिंट करें',
    'msmeCalc': '50% MSME शुल्क गणना',
  },
  'step1': {
    'title': 'चरण 1: उत्पाद प्रोफ़ाइल और विवरण',
    'subtitle': 'बीआईएस अनुपालन को अनुकूलित करने के लिए उत्पाद श्रेणी और निर्माण मापदंडों की पुष्टि करें।',
    'productName': 'उत्पाद का नाम',
    'category': 'उत्पाद उद्योग श्रेणी',
    'scale': 'उद्योग का पैमाना (MSME रियायत)',
    'location': 'निर्माण इकाई का स्थान',
    'domestic': 'घरेलू भारतीय निर्माता',
    'foreign': 'विदेशी निर्माता (FMCS)',
    'microScale': 'सूक्ष्म उद्यम (उद्यम के साथ 50% छूट)',
    'smallScale': 'लघु उद्यम (20% छूट)',
    'mediumScale': 'मध्यम उद्यम',
    'largeScale': 'बड़ा उद्योग',
    'startupScale': 'DPIIT मान्यता प्राप्त / महिला स्टार्टअप (50% छूट)',
    'continueBtn': 'लागू मानक पर आगे बढ़ें',
  },
  'step2': {
    'title': 'चरण 2: लागू भारतीय मानक (IS Code)',
    'subtitle': 'इस उत्पाद को नियंत्रित करने वाला आधिकारिक भारतीय मानक विनिर्देश, कार्यक्षेत्र और तकनीकी पैरामीटर।',
    'codeLabel': 'निर्दिष्ट भारतीय मानक (IS कोड)',
    'whyApplies': 'यह मानक क्यों लागू होता है',
    'scope': 'मानक का कार्यक्षेत्र एवं विवरण',
    'relatedStandards': 'संबंधित / संदर्भित मानक',
    'officialSource': 'आधिकारिक बीआईएस स्रोत',
    'viewOfficialDoc': 'आधिकारिक बीआईएस पोर्टल पर देखें',
    'continueBtn': 'प्रमाणीकरण एवं QCO पर आगे बढ़ें',
  },
  'step3': {
    'title': 'चरण 3: प्रमाणीकरण योजना और अनिवार्यता (QCO)',
    'subtitle': 'विनियामक अनुपालन योजना, अनिवार्य गुणवत्ता नियंत्रण आदेश (QCO) और कानूनी स्थिति।',
    'applicability': 'नियामक प्रयोज्यता स्थिति',
    'mandatoryNotice': 'गुणवत्ता नियंत्रण आदेश (QCO) के तहत कानूनन अनिवार्य',
    'voluntaryNotice': 'स्वैच्छिक गुणवत्ता प्रमाणीकरण',
    'schemeType': 'लागू प्रमाणीकरण योजना',
    'conditions': 'मुख्य अनुपालन शर्तें और छूट',
    'continueBtn': 'परीक्षण आवश्यकताओं पर आगे बढ़ें',
  },
  'step4': {
    'title': 'चरण 4: अनिवार्य प्रयोगशाला परीक्षण',
    'subtitle': 'मानक के तहत आवश्यक परीक्षण प्रोटोकॉल, पैरामीटर सीमाएं और प्रयोगशाला सुविधाएं।',
    'requiredTests': 'प्रमुख नियमित एवं स्वीकृति परीक्षण',
    'labInfo': 'परीक्षण सुविधा और प्रयोगशाला नेटवर्क',
    'continueBtn': 'दस्तावेज तैयारी पर आगे बढ़ें',
  },
  'step5': {
    'title': 'चरण 5: आवश्यक वैधानिक दस्तावेज चेकलिस्ट',
    'subtitle': 'आवेदन जमा करने से पहले ये तकनीकी फाइलें, अंशांकन प्रमाण पत्र और लेआउट तैयार करें।',
    'checklistTitle': 'आवेदन के लिए आवश्यक दस्तावेज',
    'continueBtn': 'आवेदन प्रक्रिया पर आगे बढ़ें',
  },
  'step6': {
    'title': 'चरण 6: चरण-दर-चरण आवेदन एवं लाइसेंस प्रक्रिया',
    'subtitle': 'ऑनलाइन आवेदन से लेकर CM/L लाइसेंस प्राप्त करने तक की वैधानिक प्रक्रिया।',
    'timelineTitle': 'लाइसेंसिंग मील के पत्थर और समय सीमा',
    'manakonlineCTA': 'e-BIS मानकऑनलाइन पोर्टल पर ऑनलाइन आवेदन करें',
    'restartBtn': 'नया उत्पाद गाइड शुरू करें',
  },
  'hallmarking': {
    'title': 'सोने और चांदी के आभूषणों की बीआईएस हॉलमार्किंग',
    'subtitle': 'बीआईएस अधिनियम 2016 के तहत आधिकारिक शुद्धता प्रमाणीकरण और 6-अंकीय HUID प्रणाली।',
    'searchPlaceholder': 'हॉलमार्किंग संबंधी प्रश्न पूछें (जैसे हॉलमार्क के 3 अनिवार्य चिह्न क्या हैं?, HUID कैसे सत्यापित करें?)...',
    'askBtn': 'हॉलमार्किंग सहायक से पूछें',
  },
  'demonstration': {
    'title': 'प्रदर्शन: बीआईएस अनुपालन एवं प्रमाणीकरण यात्रा',
    'subtitle': 'निर्माताओं और जौहरियों के लिए संपूर्ण वैधानिक प्रक्रिया को दर्शाने वाला इंटरैक्टिव और संपादन योग्य वर्कफ़्लो इंजन।',
    'addStep': '+ नया चरण जोड़ें',
    'resetFlow': 'डिफ़ॉल्ट प्रवाह रीसेट करें',
    'productFlowTab': 'उत्पाद प्रमाणीकरण (ISI/CRS)',
    'hallmarkingFlowTab': 'स्वर्ण एवं रजत हॉलमार्किंग (HUID)',
  },
  'consumer': {
    'title': 'बीआईएस उपभोक्ता सहायता एवं सत्यापन गेटवे',
    'subtitle': 'उपभोक्ताओं को प्रामाणिक ISI चिह्न सत्यापित करने, HUID आभूषण शुद्धता जांचने और घटिया सामान की रिपोर्ट करने में सक्षम बनाना।',
    'searchPlaceholder': 'उपभोक्ता प्रश्न पूछें (जैसे BIS Care ऐप पर CML नंबर कैसे सत्यापित करें?, नकली ISI मार्क की शिकायत कैसे करें?)...',
  },
  'assistant': {
    'title': 'बीआईएस एआई अनुपालन सहायक',
    'subtitle': 'वास्तविक समय में प्रश्न पूछें, मानक सत्यापन के लिए पीडीएफ या उत्पाद फोटो अपलोड करें।',
    'inputPlaceholder': 'इस उत्पाद, मानक या लैब के बारे में प्रश्न पूछें...',
    'sendBtn': 'भेजें',
    'upload': 'PDF / फोटो अपलोड',
    'noInfoTitle': 'वर्तमान दस्तावेज़ अनुक्रमणिका में जानकारी उपलब्ध नहीं है',
    'noInfoDesc': 'यह विशिष्ट विवरण सक्रिय बीआईएस वेक्टर ज्ञानकोष से प्राप्त नहीं हुआ। आप दाईं ओर एआई सहायक में केंद्रित प्रश्न पूछ सकते हैं।',
  },
  'common': {
    'verifiedSource': 'सत्यापित बीआईएस स्रोत',
    'page': 'पृष्ठ',
  },
  # Flat aliases
  's1Title': 'चरण 1: उत्पाद प्रोफ़ाइल और विवरण',
  's1Subtitle': 'बीआईएस अनुपालन को अनुकूलित करने के लिए उत्पाद श्रेणी और निर्माण मापदंडों की पुष्टि करें।',
  's1ProductName': 'उत्पाद का नाम',
  's1Category': 'उत्पाद उद्योग श्रेणी',
  's1Scale': 'उद्योग का पैमाना (MSME रियायत)',
  's1Location': 'निर्माण इकाई का स्थान',
  's1Domestic': 'घरेलू भारतीय निर्माता',
  's1Foreign': 'विदेशी निर्माता (FMCS)',
  's1MicroScale': 'सूक्ष्म उद्यम (उद्यम के साथ 50% छूट)',
  's1SmallScale': 'लघु उद्यम (20% छूट)',
  's1MediumScale': 'मध्यम उद्यम',
  's1LargeScale': 'बड़ा उद्योग',
  's1StartupScale': 'DPIIT मान्यता प्राप्त / महिला स्टार्टअप (50% छूट)',
  's1ContinueBtn': 'लागू मानक पर आगे बढ़ें',
  's2Title': 'चरण 2: लागू भारतीय मानक (IS Code)',
  's2Subtitle': 'इस उत्पाद को नियंत्रित करने वाला आधिकारिक भारतीय मानक विनिर्देश, कार्यक्षेत्र और तकनीकी पैरामीटर।',
  's2WhyApplies': 'यह मानक क्यों लागू होता है',
  's2Scope': 'मानक का कार्यक्षेत्र एवं विवरण',
  's2RelatedStandards': 'संबंधित / संदर्भित मानक',
  's2OfficialSource': 'आधिकारिक बीआईएस स्रोत',
  's2ViewOfficialDoc': 'आधिकारिक बीआईएस पोर्टल पर देखें',
  's2ContinueBtn': 'प्रमाणीकरण एवं QCO पर आगे बढ़ें',
  's3Title': 'चरण 3: प्रमाणीकरण योजना और अनिवार्यता (QCO)',
  's3Subtitle': 'विनियामक अनुपालन योजना, अनिवार्य गुणवत्ता नियंत्रण आदेश (QCO) और कानूनी स्थिति।',
  's3Applicability': 'नियामक प्रयोज्यता स्थिति',
  's3MandatoryNotice': 'गुणवत्ता नियंत्रण आदेश (QCO) के तहत कानूनन अनिवार्य',
  's3VoluntaryNotice': 'स्वैच्छिक गुणवत्ता प्रमाणीकरण',
  's3Conditions': 'मुख्य अनुपालन शर्तें और छूट',
  's3ContinueBtn': 'परीक्षण आवश्यकताओं पर आगे बढ़ें',
  's4Title': 'चरण 4: अनिवार्य प्रयोगशाला परीक्षण',
  's4Subtitle': 'मानक के तहत आवश्यक परीक्षण प्रोटोकॉल, पैरामीटर सीमाएं और प्रयोगशाला सुविधाएं।',
  's4RequiredTests': 'प्रमुख नियमित एवं स्वीकृति परीक्षण',
  's4LabInfo': 'परीक्षण सुविधा और प्रयोगशाला नेटवर्क',
  's4ContinueBtn': 'दस्तावेज तैयारी पर आगे बढ़ें',
  's5Title': 'चरण 5: आवश्यक वैधानिक दस्तावेज चेकलिस्ट',
  's5Subtitle': 'आवेदन जमा करने से पहले ये तकनीकी फाइलें, अंशांकन प्रमाण पत्र और लेआउट तैयार करें।',
  's5ContinueBtn': 'आवेदन प्रक्रिया पर आगे बढ़ें',
  's6Title': 'चरण 6: चरण-दर-चरण आवेदन एवं लाइसेंस प्रक्रिया',
  's6Subtitle': 'ऑनलाइन आवेदन से लेकर CM/L लाइसेंस प्राप्त करने तक की वैधानिक प्रक्रिया।',
  's6TimelineTitle': 'लाइसेंसिंग मील के पत्थर और समय सीमा',
  's6ManakonlineCTA': 'e-BIS मानकऑनलाइन पोर्टल पर ऑनलाइन आवेदन करें',
  's6RestartBtn': 'नया उत्पाद गाइड शुरू करें',
  'prevStepBtn': '← पिछला चरण',
  'printGuideBtn': 'गाइड प्रिंट करें',
  'newConsultationBtn': 'नई उत्पाद परामर्श',
  'guideTitle': 'बीआईएस उत्पाद प्रमाणीकरण गाइड',
  'guideSubtitle': 'चरण-दर-चरण विनियामक अनुपालन रोडमैप:',
  'step1Label': 'उत्पाद प्रोफ़ाइल',
  'step2Label': 'लागू मानक',
  'step3Label': 'प्रमाणीकरण एवं QCO',
  'step4Label': 'परीक्षण एवं लैब्स',
  'step5Label': 'दस्तावेज',
  'step6Label': 'आवेदन प्रक्रिया',
}

bn_dict = {
  'gov': {
    'india': 'ভারত সরকার',
    'indiaHindi': 'ভারত সরকার',
    'ministry': 'ভোক্তা বিষয়ক, খাদ্য ও গণবন্টন মন্ত্রক',
    'manakonline': 'মানকঅনলাইন (e-BIS)',
    'standardsPortal': 'আপনার মানক জানুন (BIS Standards)',
    'officialPortal': 'বিআইএস অফিসিয়াল পোর্টাল',
  },
  'brand': {
    'title': 'ব্যুরো অফ ইন্ডিয়ান স্ট্যান্ডার্ডস (BIS)',
    'subTitle': 'ভারতের জাতীয় মানক সংস্থা • এআই সম্মতি সহায়ক',
    'motto': 'মানক: পথপ্রদর্শক: (মানক পথ দেখায়)',
    'tagAI': 'এআই সম্মতি পোর্টাল',
    'ragActive': 'RAG সার্ভার সক্রিয়',
    'ragOffline': 'সার্ভার অফলাইন',
    'installApp': 'অ্যাপ ইনস্টল করুন',
    'appInstalled': 'অ্যাপ ইনস্টল করা হয়েছে',
  },
  'nav': {
    'home': 'পণ্য গাইড',
    'chat': 'এআই সহায়ক',
    'standards': 'মানক ও QCO',
    'certification': 'সার্টিফিকেশন',
    'labs': 'পরীক্ষাগার ও ল্যাব',
    'hallmarking': 'হলমার্কিং',
    'demonstration': 'প্রক্রিয়া প্রবাহ',
    'estimator': 'ফি গণক (MSME)',
    'consumer': 'ভোক্তা সহায়তা',
  },
  'hero': {
    'badge': 'জাতীয় মানক সম্মতি গেটওয়ে • SIH সমস্যা বিবৃতি 26107',
    'titlePrefix': 'আপনার নির্দেশিকা:',
    'titleStandards': 'বিআইএস মানক',
    'titleAnd': 'ও',
    'titleCert': 'সার্টিফিকেশন',
    'subtitle': 'প্রযোজ্য ভারতীয় মানক খুঁজুন, গুণমান নিয়ন্ত্রণ আদেশ (QCO) যাচাই করুন, পরীক্ষার প্রয়োজনীয়তা বুঝুন এবং যাচাইকৃত অফিসিয়াল বিআইএস উৎস পান।',
    'inputLabel': 'আপনার পণ্য বা সার্টিফিকেশন প্রয়োজনীয়তা সম্পর্কে বলুন:',
    'inputPlaceholder': 'উদাহরণ: আমি বৈদ্যুতিক ইস্ত্রি তৈরি করি। আমাকে কোন বিআইএস মানক, QCO নিয়ম এবং পরীক্ষার প্রক্রিয়া অনুসরণ করতে হবে?',
    'productNameLabel': 'পণ্যের নাম',
    'productNamePlaceholder': 'उदा. বৈদ্যুতিক ইস্ত্রি, এলইডি বাল্ব, প্যাকেজড পানীয় জল',
    'categoryLabel': 'শিল্প বিভাগ',
    'scaleLabel': 'শিল্পের মাত্রা (MSME ছাড়)',
    'locationLabel': 'উৎপাদন ইউনিটের অবস্থান',
    'locationPlaceholder': 'उदा. নয়ডা, উত্তর প্রদেশ / মুম্বাই, মহারাষ্ট্র',
    'domesticLabel': 'দেশীয় ভারতীয় প্রস্তুতকারক',
    'foreignLabel': 'বিদেশী প্রস্তুতকারক (FMCS)',
    'attachPhoto': 'PDF / পণ্যের ছবি সংযুক্ত করুন',
    'attachShort': 'সংযুক্ত করুন',
    'voiceQuery': 'কণ্ঠে জিজ্ঞাসা করুন',
    'listening': 'শুনছে...',
    'startGuide': 'পণ্য সার্টিফিকেশন গাইড শুরু করুন',
    'analyzing': 'RAG ব্যাকএন্ড দিয়ে মানক বিশ্লেষণ করা হচ্ছে...',
    'samplePrompts': 'সাধারণ পণ্যের প্রশ্নাবলী দেখুন:',
  },
  'productGuide': {
    'title': 'বিআইএস পণ্য সার্টিফিকেশন গাইড',
    'subtitle': 'ধাপে ধাপে নিয়ন্ত্রক সম্মতি রোডম্যাপ:',
    'step1': 'পণ্যের প্রোফাইল',
    'step2': 'প্রযোজ্য মানক',
    'step3': 'সার্টিফিকেশন ও QCO',
    'step4': 'পরীক্ষা ও ল্যাব',
    'step5': 'নথিপত্র',
    'step6': 'আবেদন প্রক্রিয়া',
    'prevStep': '← পূর্ববর্তী ধাপ',
    'newConsultation': 'নতুন পণ্য পরামর্শ',
    'printGuide': 'গাইড প্রিন্ট করুন',
    'msmeCalc': '৫০% MSME ফি গণক',
  },
  'step1': {
    'title': 'ধাপ ১: পণ্যের প্রোফাইল ও বিবরণ',
    'subtitle': 'বিআইএস সম্মতির জন্য পণ্যের বিভাগ এবং উৎপাদন প্যারামিটার নিশ্চিত করুন।',
    'productName': 'পণ্যের নাম',
    'category': 'পণ্যের শিল্প বিভাগ',
    'scale': 'শিল্পের মাত্রা (MSME ছাড়)',
    'location': 'উৎপাদন ইউনিটের অবস্থান',
    'domestic': 'দেশীয় ভারতীয় প্রস্তুতকারক',
    'foreign': 'বিদেশী প্রস্তুতকারক (FMCS)',
    'microScale': 'মাইক্রো এন্টারপ্রাইজ (উদ্যমের সাথে ৫০% ছাড়)',
    'smallScale': 'ক্ষুদ্র উদ্যোগ (২০% ছাড়)',
    'mediumScale': 'মাঝারি শিল্প',
    'largeScale': 'বৃহৎ শিল্প',
    'startupScale': 'DPIIT স্বীকৃত / মহিলা স্টার্টআপ (৫০% ছাড়)',
    'continueBtn': 'প্রযোজ্য মানকে এগিয়ে যান',
  },
  'step2': {
    'title': 'ধাপ ২: প্রযোজ্য ভারতীয় মানক (IS Code)',
    'subtitle': 'এই পণ্যকে নিয়ন্ত্রণকারী অফিসিয়াল ভারতীয় মানক স্পেসিফিকেশন এবং প্রযুক্তিগত পরামিতি।',
    'codeLabel': 'নির্দিষ্ট ভারতীয় মানক (IS কোড)',
    'whyApplies': 'এই মানকটি কেন প্রযোজ্য',
    'scope': 'মানকের পরিধি ও কভারেজ',
    'relatedStandards': 'সম্পর্কিত / উল্লেখিত মানকসমূহ',
    'officialSource': 'অফিসিয়াল বিআইএস উৎস',
    'viewOfficialDoc': 'অফিসিয়াল বিআইএস পোর্টালে দেখুন',
    'continueBtn': 'সার্টিফিকেশন ও QCO-তে এগিয়ে যান',
  },
  'step3': {
    'title': 'ধাপ ৩: সার্টিফিকেশন স্কিম ও বাধ্যবাধকতা (QCO)',
    'subtitle': 'নিয়ন্ত্রক সম্মতি স্কিম, বাধ্যতামূলক গুণমান নিয়ন্ত্রণ আদেশ (QCO) এবং আইনি অবস্থা।',
    'applicability': 'নিয়ন্ত্রক প্রযোজ্যতা স্থিতি',
    'mandatoryNotice': 'গুণমান নিয়ন্ত্রণ আদেশ (QCO) এর অধীনে আইনত বাধ্যতামূলক',
    'voluntaryNotice': 'স্বেচ্ছামূলক গুণমান সার্টিফিকেশন',
    'schemeType': 'প্রযোজ্য সার্টিফিকেশন স্কিম',
    'conditions': 'প্রধান সম্মতি শর্তাবলী ও ছাড়',
    'continueBtn': 'পরীক্ষার প্রয়োজনীয়তায় এগিয়ে যান',
  },
  'step4': {
    'title': 'ধাপ ৪: বাধ্যতামূলক পরীক্ষাগার পরীক্ষা',
    'subtitle': 'মানকের অধীনে প্রয়োজনীয় পরীক্ষার প্রোটোকল, প্যারামিটার সীমা এবং পরীক্ষাগারের সুবিধা।',
    'requiredTests': 'প্রধান নিয়মিত ও গ্রহণযোগ্যতা পরীক্ষা',
    'labInfo': 'পরীক্ষা সুবিধা এবং পরীক্ষাগার নেটওয়ার্ক',
    'continueBtn': 'নথিপত্র প্রস্তুতিতে এগিয়ে যান',
  },
  'step5': {
    'title': 'ধাপ ৫: প্রয়োজনীয় সংবিধিবদ্ধ নথিপত্রের চেকলিস্ট',
    'subtitle': 'আবেদন জমা দেওয়ার আগে প্রযুক্তিগত ফাইল, ক্যালিব্রেশন সার্টিফিকেট এবং লেআউট প্রস্তুত করুন।',
    'checklistTitle': 'আবেদনের জন্য প্রয়োজনীয় নথিপত্র',
    'continueBtn': 'আবেদন প্রক্রিয়ায় এগিয়ে যান',
  },
  'step6': {
    'title': 'ধাপ ৬: ধাপে ধাপে আবেদন ও লাইসেন্স প্রক্রিয়া',
    'subtitle': 'অনলাইন আবেদন থেকে শুরু করে CM/L লাইসেন্স প্রদান পর্যন্ত সংবিধিবদ্ধ প্রক্রিয়া।',
    'timelineTitle': 'লাইসেন্সিং মাইলফলক ও সময়সীমা',
    'manakonlineCTA': 'e-BIS মানকঅনলাইন পোর্টালে অনলাইনে আবেদন করুন',
    'restartBtn': 'নতুন পণ্য গাইড শুরু করুন',
  },
  'hallmarking': {
    'title': 'স্বর্ণ ও রৌপ্য অলঙ্কারের বিআইএস হলমার্কিং',
    'subtitle': 'বিআইএস আইন ২০১৬ এর অধীনে অফিসিয়াল বিশুদ্ধতা সার্টিফিকেশন এবং ৬-সংখ্যার HUID সিস্টেম।',
    'searchPlaceholder': 'হলমার্কিং সংক্রান্ত প্রশ্ন জিজ্ঞাসা করুন (যেমন হলমার্কের ৩টি বাধ্যতামূলক চিহ্ন কি কি?, HUID কিভাবে যাচাই করবেন?)...',
    'askBtn': 'হলমার্কিং সহায়ককে জিজ্ঞাসা করুন',
  },
  'demonstration': {
    'title': 'প্রদর্শন: বিআইএস সম্মতি ও সার্টিফিকেশন যাত্রা',
    'subtitle': 'উত্পাদক এবং স্বর্ণকারদের জন্য সম্পূর্ণ সংবিধিবদ্ধ প্রক্রিয়া প্রদর্শনকারী ইন্টারেক্টিভ ও সম্পাদনাযোগ্য ওয়ার্কফ্লো ইঞ্জিন।',
    'addStep': '+ নতুন পদক্ষেপ যোগ করুন',
    'resetFlow': 'ডিফল্ট প্রবাহ রিসেট করুন',
    'productFlowTab': 'পণ্য সার্টিফিকেশন (ISI/CRS)',
    'hallmarkingFlowTab': 'স্বর্ণ ও রৌপ্য হলমার্কিং (HUID)',
  },
  'consumer': {
    'title': 'বিআইএস ভোক্তা সহায়তা ও যাচাইকরণ গেটওয়ে',
    'subtitle': 'ভোক্তাদের খাঁটি ISI চিহ্ন যাচাই করতে, HUID গহনার বিশুদ্ধতা পরীক্ষা করতে এবং নিম্নমানের পণ্যের অভিযোগ জানাতে সক্ষম করা।',
    'searchPlaceholder': 'ভোক্তা প্রশ্ন জিজ্ঞাসা করুন (যেমন BIS Care অ্যাপে CML নম্বর কিভাবে যাচাই করবেন?, নকল ISI চিহ্নের অভিযোগ কিভাবে করবেন?)...',
  },
  'assistant': {
    'title': 'বিআইএস এআই সম্মতি সহায়ক',
    'subtitle': 'রিয়েল-টাইমে প্রশ্ন জিজ্ঞাসা করুন, মানক যাচাইয়ের জন্য পিডিএফ বা পণ্যের ছবি আপলোড করুন।',
    'inputPlaceholder': 'এই পণ্য, মানক বা ল্যাব সম্পর্কে জিজ্ঞাসা করুন...',
    'sendBtn': 'পাঠান',
    'upload': 'PDF / ছবি আপলোড',
    'noInfoTitle': 'বর্তমান নথি সূচীতে তথ্য উপলব্ধ নেই',
    'noInfoDesc': 'এই নির্দিষ্ট বিবরণটি সক্রিয় বিআইএস ভেক্টর জ্ঞানভাণ্ডার থেকে পাওয়া যায়নি। আপনি ডানদিকের এআই সহায়কে নির্দিষ্ট প্রশ্ন জিজ্ঞাসা করতে পারেন।',
  },
  'common': {
    'verifiedSource': 'যাচাইকৃত বিআইএস উৎস',
    'page': 'পৃষ্ঠা',
  },
  # Flat aliases
  's1Title': 'ধাপ ১: পণ্যের প্রোফাইল ও বিবরণ',
  's1Subtitle': 'বিআইএস সম্মতির জন্য পণ্যের বিভাগ এবং উৎপাদন প্যারামিটার নিশ্চিত করুন।',
  's1ProductName': 'পণ্যের নাম',
  's1Category': 'পণ্যের শিল্প বিভাগ',
  's1Scale': 'শিল্পের মাত্রা (MSME ছাড়)',
  's1Location': 'উৎপাদন ইউনিটের অবস্থান',
  's1Domestic': 'দেশীয় ভারতীয় প্রস্তুতকারক',
  's1Foreign': 'বিদেশী প্রস্তুতকারক (FMCS)',
  's1MicroScale': 'মাইক্রো এন্টারপ্রাইজ (উদ্যমের সাথে ৫০% ছাড়)',
  's1SmallScale': 'ক্ষুদ্র উদ্যোগ (২০% ছাড়)',
  's1MediumScale': 'মাঝারি শিল্প',
  's1LargeScale': 'বৃহৎ শিল্প',
  's1StartupScale': 'DPIIT স্বীকৃত / মহিলা স্টার্টআপ (৫০% ছাড়)',
  's1ContinueBtn': 'প্রযোজ্য মানকে এগিয়ে যান',
  's2Title': 'ধাপ ২: প্রযোজ্য ভারতীয় মানক (IS Code)',
  's2Subtitle': 'এই পণ্যকে নিয়ন্ত্রণকারী অফিসিয়াল ভারতীয় মানক স্পেসিফিকেশন এবং প্রযুক্তিগত পরামিতি।',
  's2WhyApplies': 'এই মানকটি কেন প্রযোজ্য',
  's2Scope': 'মানকের পরিধি ও কভারেজ',
  's2RelatedStandards': 'সম্পর্কিত / উল্লেখিত মানকসমূহ',
  's2OfficialSource': 'অফিসিয়াল বিআইএস উৎস',
  's2ViewOfficialDoc': 'অফিসিয়াল বিআইএস পোর্টালে দেখুন',
  's2ContinueBtn': 'সার্টিফিকেশন ও QCO-তে এগিয়ে যান',
  's3Title': 'ধাপ ৩: সার্টিফিকেশন স্কিম ও বাধ্যবাধকতা (QCO)',
  's3Subtitle': 'নিয়ন্ত্রক সম্মতি স্কিম, বাধ্যতামূলক গুণমান নিয়ন্ত্রণ আদেশ (QCO) এবং আইনি অবস্থা।',
  's3Applicability': 'নিয়ন্ত্রক প্রযোজ্যতা স্থিতি',
  's3MandatoryNotice': 'গুণমান নিয়ন্ত্রণ আদেশ (QCO) এর অধীনে আইনত বাধ্যতামূলক',
  's3VoluntaryNotice': 'স্বেচ্ছামূলক গুণমান সার্টিফিকেশন',
  's3Conditions': 'প্রধান সম্মতি শর্তাবলী ও ছাড়',
  's3ContinueBtn': 'পরীক্ষার প্রয়োজনীয়তায় এগিয়ে যান',
  's4Title': 'ধাপ ৪: বাধ্যতামূলক পরীক্ষাগার পরীক্ষা',
  's4Subtitle': 'মানকের অধীনে প্রয়োজনীয় পরীক্ষার প্রোটোকল, প্যারামিটার সীমা এবং পরীক্ষাগারের সুবিধা।',
  's4RequiredTests': 'প্রধান নিয়মিত ও গ্রহণযোগ্যতা পরীক্ষা',
  's4LabInfo': 'পরীক্ষা সুবিধা এবং পরীক্ষাগার নেটওয়ার্ক',
  's4ContinueBtn': 'নথিপত্র প্রস্তুতিতে এগিয়ে যান',
  's5Title': 'ধাপ ৫: প্রয়োজনীয় সংবিধিবদ্ধ নথিপত্রের চেকলিস্ট',
  's5Subtitle': 'আবেদন জমা দেওয়ার আগে প্রযুক্তিগত ফাইল, ক্যালিব্রেশন সার্টিফিকেট এবং লেআউট প্রস্তুত করুন।',
  's5ContinueBtn': 'আবেদন প্রক্রিয়ায় এগিয়ে যান',
  's6Title': 'ধাপ ৬: ধাপে ধাপে আবেদন ও লাইসেন্স প্রক্রিয়া',
  's6Subtitle': 'অনলাইন আবেদন থেকে শুরু করে CM/L লাইসেন্স প্রদান পর্যন্ত সংবিধিবদ্ধ প্রক্রিয়া।',
  's6TimelineTitle': 'লাইসেন্সিং মাইলফলক ও সময়সীমা',
  's6ManakonlineCTA': 'e-BIS মানকঅনলাইন পোর্টালে অনলাইনে আবেদন করুন',
  's6RestartBtn': 'নতুন পণ্য গাইড শুরু করুন',
  'prevStepBtn': '← পূর্ববর্তী ধাপ',
  'printGuideBtn': 'গাইড প্রিন্ট করুন',
  'newConsultationBtn': 'নতুন পণ্য পরামর্শ',
  'guideTitle': 'বিআইএস পণ্য সার্টিফিকেশন গাইড',
  'guideSubtitle': 'ধাপে ধাপে নিয়ন্ত্রক সম্মতি রোডম্যাপ:',
  'step1Label': 'পণ্যের প্রোফাইল',
  'step2Label': 'প্রযোজ্য মানক',
  'step3Label': 'সার্টিফিকেশন ও QCO',
  'step4Label': 'পরীক্ষা ও ল্যাব',
  'step5Label': 'নথিপত্র',
  'step6Label': 'আবেদন প্রক্রিয়া',
}

def to_ts_content(name, d):
    return "export const " + name + " = " + json.dumps(d, ensure_ascii=False, indent=2) + ";\n"

with open('frontend/src/i18n/locales/en.ts', 'w', encoding='utf-8') as f:
    f.write(to_ts_content('en', en_dict))

with open('frontend/src/i18n/locales/hi.ts', 'w', encoding='utf-8') as f:
    f.write(to_ts_content('hi', hi_dict))

with open('frontend/src/i18n/locales/bn.ts', 'w', encoding='utf-8') as f:
    f.write(to_ts_content('bn', bn_dict))

print('LOCALES_GENERATED')
